/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Net1Part2_Chatting;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Scanner;
import java.util.Set;
import java.util.TimerTask;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author USER
 */
public class ServerFrame extends javax.swing.JFrame{
    /**
     * Creates new form Server
     */
    public ServerFrame() {
        
        initComponents();
        textPaneArea.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        tcpPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneArea = new javax.swing.JTextPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        status = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TCP Server");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        start.setBackground(new java.awt.Color(229, 193, 205));
        start.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        start.setText("Start Listening");
        start.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel1.add(start);
        start.setBounds(30, 430, 131, 30);

        tcpPort.setBackground(new java.awt.Color(204, 204, 255));
        tcpPort.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tcpPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcpPortActionPerformed(evt);
            }
        });
        jPanel1.add(tcpPort);
        tcpPort.setBounds(120, 270, 170, 30);

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Port :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 270, 50, 27);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textPaneArea.setBackground(new java.awt.Color(204, 204, 255));
        textPaneArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(textPaneArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 130, 346, 271);

        jComboBox1.setBackground(new java.awt.Color(229, 193, 205));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loopback Pseudo-Interface 1: 127.0.0.1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 51, 51)));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(310, 30, 370, 40);

        userList.setBackground(new java.awt.Color(204, 204, 255));
        userList.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(userList);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(740, 130, 214, 330);

        status.setBackground(new java.awt.Color(255, 255, 255));
        status.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        status.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        status.setText("the State here");
        jPanel1.add(status);
        status.setBounds(380, 430, 300, 34);

        jLabel11.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Status :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(310, 430, 57, 34);

        jButton1.setBackground(new java.awt.Color(229, 193, 205));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Add user");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 380, 130, 30);

        txtUsername.setBackground(new java.awt.Color(204, 204, 255));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername);
        txtUsername.setBounds(120, 130, 170, 30);

        txtPass.setBackground(new java.awt.Color(204, 204, 255));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtPass);
        txtPass.setBounds(120, 192, 170, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("username:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 130, 100, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 200, 80, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Create New User");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 66, 160, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("User Online");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(770, 100, 151, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcpPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcpPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcpPortActionPerformed
     
    private ServerSocket socket;
    private HashMap<String, Socket> clientsHash = new HashMap<>();
    private HashMap<String, LocalDateTime> lastActiveTime = new HashMap<>();
    private HashMap<String, String> statusMap = new HashMap<>();
    private boolean t = false;

 
   
    
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        int portNumber = 0000;
        boolean isNumbers = false;
       
        try {
            if (!tcpPort.getText().isEmpty()) {
                portNumber = Integer.parseInt(tcpPort.getText());
                isNumbers = true;
                if (isNumbers) {
                    socket = new ServerSocket(portNumber);
                    StyledDocument doc = textPaneArea.getStyledDocument();
                    Style style = textPaneArea.addStyle("", null);
                    StyleConstants.setForeground(style, Color.BLUE);
                    StyleConstants.setBackground(style, Color.white);
                    String s1 = "Start Listening at port: " + portNumber + "\n";
                    doc.insertString(doc.getLength(), s1, style);
                     new ClientAccept(socket).start();
        status.setText("Address: " + InetAddress.getByName("localhost").getHostAddress() + ", port: " + portNumber);
        startTimerTask(); // Start the timer task to check for inactive users
    }
            } else {
                JOptionPane.showMessageDialog(null, "pleace enter a port number in 'port number' field.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "pleace enter only a numbers in 'port number' field.");
            isNumbers = false;
        } catch (IOException | BadLocationException ex) {
            JOptionPane.showMessageDialog(null, "The port number is used");
             //               Logger.getLogger(ClientAccept.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_startActionPerformed
 public static boolean checkUsernameExistence(String username) {
        String FILENAME;
        try  {
           Scanner scanner = new Scanner(new File("accounts.txt")); 
         while(scanner.hasNext()){
             String []tokens=scanner.nextLine().split(" ");
             if(tokens[0].equalsIgnoreCase(username))
                 return true;
            }
         return false;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false;
    }
 
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(checkUsernameExistence(txtUsername.getText()))  {
            JOptionPane.showMessageDialog(null, "Error: This username already exists!", "Existing User Error", JOptionPane.ERROR_MESSAGE);
       }
       else {
           String tokenz=txtUsername.getText()+" "+txtPass.getText();
            try (FileOutputStream outToFile = new FileOutputStream("accounts.txt", true);) 
             {   
                outToFile.write(("\n"+tokenz).getBytes());
                JOptionPane.showMessageDialog(null, "Added successfully !", "successfully", JOptionPane.INFORMATION_MESSAGE);
                outToFile.close();
            }
            catch (FileNotFoundException ex) {
               Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IOException ex) {
               Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
            
            String[] field={txtUsername.getText(),"2024-03-22|00:00:00"};
            Client.list.add(field);
       }
       txtUsername.setText("");
       txtPass.setText("");
       tcpPort.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private class ClientAccept extends Thread {

        private ServerSocket socket;

        public ClientAccept(ServerSocket socket) {
            this.socket = socket;

        }

        public void run() {
            while (true) {
                try {
                    Socket clientSocket = socket.accept();
                    String username = new DataInputStream(clientSocket.getInputStream()).readUTF();
                    DataOutputStream dataOutOfClient = new DataOutputStream(clientSocket.getOutputStream());
                    if (clientsHash.containsKey(username)) {
                        dataOutOfClient.writeUTF("founded");
                    } else {
                        clientsHash.put(username, clientSocket);
                        lastActiveTime.put(username, LocalDateTime.now()); // Set initial active time
                        statusMap.put(username, "Active"); // Set initial status
                        addTextToArea(username, true);
                        dataOutOfClient.writeUTF("accept");
                        new endToEndList().start();
                        new ReadMessage(clientSocket, username).start();        
                    
                    }
                       /* else {
                        clientsHash.put(username, clientSocket);
                        addTextToArea(username, true);
                        dataOutOfClient.writeUTF("accept");
                        new endToEndList().start();
                        new ReadMessage(clientSocket, username).start();
                    }*/

                } catch (IOException ex) {
                    Logger.getLogger(ClientAccept.class.getName()).log(Level.SEVERE, null, ex);
                } catch (BadLocationException ex) {
                    Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }

    }
    class ReadMessage extends Thread {

        Socket s;
        String ID;

        ReadMessage(Socket s, String username) {
            this.s = s;
            this.ID = username;

        }

        public void run() {

            while (!clientsHash.isEmpty() && clientsHash.containsKey(ID)) {
                try {
                    String in = new DataInputStream(s.getInputStream()).readUTF();
                    if (in.contains("logout")) {
                       
                        new DataOutputStream(((Socket) clientsHash.get(ID)).getOutputStream()).writeUTF("logout");////////
                        
                        clientsHash.remove(ID);
                        lastActiveTime.remove(ID); // Remove last active time
                         statusMap.remove(ID); // Remove status
                        addTextToArea(ID, false,null);
                        new endToEndList().start();

                  ////////////////////
                     }  else if (in.contains("set_status")) {
                    String[] parts = in.split(":");
                    String newStatus = parts[1];
                    statusMap.put(ID, newStatus);
                    addTextToArea(ID, false, newStatus); // Update the text area with the new status
                    new endToEndList().start();
                }  else {
                        lastActiveTime.put(ID, LocalDateTime.now()); // Update last active time
                    }///////////////////////
                } catch (IOException | BadLocationException ex) {
                    clientsHash.remove(ID);
                    lastActiveTime.remove(ID); // Remove last active time
                   statusMap.remove(ID); // Remove status
                    try {
                        addTextToArea(ID, false);
                    } catch (BadLocationException ex1) {
                        Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                    new endToEndList().start();
                    ex.printStackTrace();

                }
            }
        }
    }

    private class endToEndList extends Thread {

        DefaultListModel dlm;

        public endToEndList() {
            dlm = new DefaultListModel();
            userList.setModel(dlm);
        }

         public void run() {
        try {
            String s = new String();
            Set<String> keys = clientsHash.keySet();
            Iterator<String> itr = keys.iterator();
            dlm.clear();
            while (itr.hasNext()) {
                String key = itr.next();
                s += key + "," + String.valueOf(((Socket) clientsHash.get(key)).getPort()) + ","
                     + ((Socket) clientsHash.get(key)).getInetAddress().getHostAddress() + ","
                     + statusMap.get(key) + "&?";
                String ele = key + " (" + statusMap.get(key) + ")";
                dlm.addElement(ele);
            }
            if (s.length() != 0) {
                s = s.substring(0, s.length() - 2);
            }
            itr = keys.iterator();
            while (itr.hasNext()) {
                String key = itr.next();
                try {
                    new DataOutputStream(((Socket) clientsHash.get(key)).getOutputStream()).writeUTF("add to list" + s);
                } catch (IOException ex) {
                    clientsHash.remove(key);
                    lastActiveTime.remove(key);
                    statusMap.remove(key);
                    addTextToArea(key, false, null);
                }
            }
        
         } catch (BadLocationException ex) {

          }
         }
    }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
     /*   public void run() {
            try {

                String s = new String();

                Set k = clientsHash.keySet();
                Iterator itr = k.iterator();
                dlm.clear();
                while (itr.hasNext()) {
                    String key = (String) itr.next();
                    s += key + "," + String.valueOf(((Socket) clientsHash.get(key)).getPort()) + ","
                            + ((Socket) clientsHash.get(key)).getInetAddress().getHostAddress() + ","
                            + statusMap.get(key) + "&?"; // Include the status in the list
                    String ele = ((Socket) clientsHash.get(key)).getInetAddress().getHostAddress() + ","
                    + String.valueOf(((Socket) clientsHash.get(key)).getPort()) + ","
                            + statusMap.get(key); // Include the status in the list element
                    dlm.addElement(ele);
                }
                if (s.length() != 0) {
                    s = s.substring(0, s.length() - 2);
                }
                itr = k.iterator();
                while (itr.hasNext()) {
                    String key = (String) itr.next();
                    try {
                        new DataOutputStream(((Socket) clientsHash.get(key)).getOutputStream()).writeUTF("add to list" + s);

                    } catch (IOException ex) {

                        clientsHash.remove(key);
                       lastActiveTime.remove(key); // Remove last active time
                        statusMap.remove(key); // Remove status
                        addTextToArea(key, false);

                    }
                }
            } catch (BadLocationException ex) {

            }
        }*/
    
    
    
    /*private void addTextToArea(String username, boolean color, String status) throws BadLocationException {
    StyledDocument doc = textPaneArea.getStyledDocument();
    Style style = textPaneArea.addStyle("", null);

    if (color) {
        // In login
        StyleConstants.setForeground(style, Color.BLUE);
        StyleConstants.setBackground(style, Color.white);
        String s1 = username + " (" + status + ") logged in" + "\n";
        doc.insertString(doc.getLength(), s1, style);
    } else {
        // In logout or status change
        if (status == null) {
            // Logout
            StyleConstants.setForeground(style, Color.RED);
            StyleConstants.setBackground(style, Color.white);
            String s1 = username + " logged out" + "\n";
            doc.insertString(doc.getLength(), s1, style);
        } else {
            // Status change
            switch (status) {
                case "Active":
                    StyleConstants.setForeground(style, Color.BLUE);
                    break;
                case "Busy":
                    StyleConstants.setForeground(style, Color.ORANGE);
                    break;
                case "Away":
                    StyleConstants.setForeground(style, Color.GRAY);
                    break;
            }
            StyleConstants.setBackground(style, Color.white);
            String s1 = username + " is now " + status + "\n";
            doc.insertString(doc.getLength(), s1, style);
        }
    }
}*/
    private void addTextToArea(String username, boolean color, String status) throws BadLocationException {
    if (color) {
        // In login
        StyledDocument doc = textPaneArea.getStyledDocument();
        Style style = textPaneArea.addStyle("", null);
        StyleConstants.setForeground(style, Color.BLUE);
        StyleConstants.setBackground(style, Color.white);
        String s1 = username + " (" + status + ") logged in" + "\n";
        doc.insertString(doc.getLength(), s1, style);
    } else {
        // In logout or status change
        StyledDocument doc = textPaneArea.getStyledDocument();
        Style style = textPaneArea.addStyle("", null);
        if (status == null) {
            // Logout
            StyleConstants.setForeground(style, Color.RED);
            StyleConstants.setBackground(style, Color.white);
            String s1 = username + " logged out" + "\n";
            doc.insertString(doc.getLength(), s1, style);
        } else {
            // Status change
            switch (status) {
                case "Active":
                    StyleConstants.setForeground(style, Color.BLUE);
                    break;
                case "Busy":
                    StyleConstants.setForeground(style, Color.ORANGE);
                    break;
                case "Away":
                    StyleConstants.setForeground(style, Color.GRAY);
                    break;
            }
            StyleConstants.setBackground(style, Color.white);
            String s1 = username + " is now " + status + "\n";
            doc.insertString(doc.getLength(), s1, style);
        }
    }
}

    public void addTextToArea(String username, boolean color) throws BadLocationException {
        if (color) {
            //in log in
            StyledDocument doc = textPaneArea.getStyledDocument();
            Style style = textPaneArea.addStyle("", null);
            StyleConstants.setForeground(style, Color.BLUE);
            StyleConstants.setBackground(style, Color.white);
            String s1 = username + " login" + "\n";
            doc.insertString(doc.getLength(), s1, style);
        } else {
            //in log out
            StyledDocument doc = textPaneArea.getStyledDocument();
            Style style = textPaneArea.addStyle("", null);
            StyleConstants.setForeground(style, Color.RED);
            StyleConstants.setBackground(style, Color.white);
            String s1 = username + " logout" + "\n";
            doc.insertString(doc.getLength(), s1, style);

        }

    }
    //////////////////////////////
private ScheduledExecutorService executorService;

private void startTimerTask() {
    // Start a timer task to check for inactive users
    executorService = Executors.newSingleThreadScheduledExecutor();
    executorService.scheduleAtFixedRate(new Runnable() {
        @Override
        public void run() {
            Set<String> keys = clientsHash.keySet();
            for (String key : keys) {
                LocalDateTime lastActive = lastActiveTime.get(key);
                Duration duration = Duration.between(lastActive, LocalDateTime.now());
                if (duration.getSeconds() > 30 && !statusMap.get(key).equals("Away")) {
                    // User has been inactive for more than 30 seconds, change status to "Away"
                    statusMap.put(key, "Away");
                    try {
                        addTextToArea(key, false, "Away");
                    } catch (BadLocationException ex) {
                        Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    new endToEndList().start(); // Notify other clients about the status change
                }
            }
        }
    }, 30, 30, TimeUnit.SECONDS);
}

@Override
public void dispose() {
    // Shut down the executor service when the frame is closed
    if (executorService != null) {
        executorService.shutdown();
    }
} 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton start;
    private javax.swing.JLabel status;
    private javax.swing.JTextField tcpPort;
    private javax.swing.JTextPane textPaneArea;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables

}
